
up: up-wp48-php56
stop: stop-wp48-php56

up-wp48-php56:
	docker-compose -f ./wp48/php56.yml up -d

stop-wp48-php56:
	docker-compose -f ./wp48/php56.yml stop

up-wp47-php56:
	docker-compose -f ./wp47/php56.yml up -d

stop-wp47-php56:
	docker-compose -f ./wp47/php56.yml stop

up-wp47-php71:
	docker-compose -f ./wp47/php71.yml up -d

stop-wp47-php71:
	docker-compose -f ./wp47/php71.yml stop

up-wp46-php56:
	docker-compose -f ./wp46/php56.yml up -d

stop-wp46-php56:
	docker-compose -f ./wp46/php56.yml stop

